version: '3'

services: 
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: fullstack-docker/server
    ports: 
      - '8000:8000'
    expose: 
      - 8000
    volumes: 
      - ./server:/app/server
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: fullstack-docker/client
    ports: 
      - '3000:3000'
    expose: 
      - 3000
    volumes: 
      - ./server:/app/client