version: '3'

services: 
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: fullstack-docker/server
    ports: 
      - '8000:8000'
    expose: 
      - 8000
    volumes: 
      - ./server:/usr/src/app/server
    command: yarn run server