version: '3'
networks:
  myapp:
    external: true
services: 
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: fullstack-docker/server
    ports: 
      - '8000:8000'
    expose: 
      - 8000
    volumes: 
      - ./server:/app/server
    networks: 
      - myapp
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: fullstack-docker/client
    ports: 
      - '8080:8080'
    volumes: 
      - ./server:/app/client
    networks: 
      - myapp