version: '3'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: fullstack-docker/server
    ports:
      - '8000:8000'
    expose:
      - 8000

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: fullstack-docker/client
    ports:
      - '8001:8001'
    expose:
      - 8001
